server:
  port: 8083

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15435}/task_db
    username: ${DB_USER:task_user}
    password: ${DB_PASSWORD:task_password}
    hikari:
      data-source-properties:
        TimeZone: UTC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
