server:
  port: 8083

spring:
  application:
    name: task-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15435}/task_db?options=-c%20TimeZone=UTC
    username: ${DB_USER:task_user}
    password: ${DB_PASSWORD:task_password}
    hikari:
      data-source-properties:
        TimeZone: UTC
      connection-init-sql: SET TIME ZONE 'UTC'
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
    defer-datasource-initialization: true
    properties:
      hibernate.jdbc.time_zone: UTC
  sql:
    init:
      mode: always

notifications:
  base-url: ${NOTIFICATION_SERVICE_URL:http://localhost:8084}

teams:
  base-url: ${TEAM_SERVICE_URL:http://localhost:8082}

