server:
  port: 8082

spring:
  application:
    name: team-service
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:15434}/team_db
    username: ${DB_USER:team_user}
    password: ${DB_PASSWORD:team_password}
    hikari:
      data-source-properties:
        TimeZone: UTC
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update
    open-in-view: false
